AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ImageUri:
    Type: String
    Description: The URI of the Docker image in ECR
  SSLCertificateArn:
    Type: String
    Description: ARN of the ACM SSL certificate for HTTPS
  VpcId:
    Type: String
    Description: VPC for Security Groups
  GPTKEY:
    Type: String
    Description: Access Key for GPT Access
  

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: chatbot-demo-cluster

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic to ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from ALB to ECS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        SourceSecurityGroupId: !Ref ALBSecurityGroup

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: chatbot-demo-alb
      Scheme: internet-facing
      Subnets:
            - subnet-05efd86d3373424bd
            - subnet-0cec2ad0eeb49da63
            - subnet-0f60eca4e20611767
            - subnet-0ce94da00d8e48810
            - subnet-00ca4b3185a5de62f
            - subnet-018201170b979928c
      SecurityGroups:
        - !Ref ALBSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: chatbot-target-group
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: vpc-0df761a303c14b613
      HealthCheckPath: /healthcheck
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: "443"
            StatusCode: HTTP_301
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
  
  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref SSLCertificateArn

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values: ["/*"]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
  
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: chatbot-task
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: arn:aws:iam::897722706074:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: main-container
          Image: !Ref ImageUri
          Environment:
          - Name: GPT_KEY
            Value: !Ref GPTKEY
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/chatbot-demo
              awslogs-region: us-east-1
              awslogs-stream-prefix: ecs

  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - HTTPSListener
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: main-container
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-05efd86d3373424bd
            - subnet-0cec2ad0eeb49da63
            - subnet-0f60eca4e20611767
            - subnet-0ce94da00d8e48810
            - subnet-00ca4b3185a5de62f
            - subnet-018201170b979928c
          SecurityGroups:
            - !Ref ECSSecurityGroup

Outputs:
  ServiceName:
    Value: !Ref ECSService
  TaskDefinitionArn:
    Value: !Ref TaskDefinition
